unsquashfs: add missing parameter to fix function pointer mismatch
unsquashfs.c:2233:26: error: passing argument 2 of ‘signal’ from incompatible pointer type [-Wincompatible-pointer-types]
 2233 |         signal(SIGWINCH, sigwinch_handler);
      |                          ^~~~~~~~~~~~~~~~
      |                          |
      |                          void (*)(void)
In file included from unsquashfs.h:46,
                 from unsquashfs.c:26:
/usr/include/signal.h:88:57: note: expected ‘__sighandler_t’ {aka ‘void (*)(int)’} but argument is of type ‘void (*)(void)’
   88 | extern __sighandler_t signal (int __sig, __sighandler_t __handler)
      |                                          ~~~~~~~~~~~~~~~^~~~~~~~~
unsquashfs.c:142:6: note: ‘sigwinch_handler’ declared here
  142 | void sigwinch_handler()
      |      ^~~~~~~~~~~~~~~~
/usr/include/signal.h:72:16: note: ‘__sighandler_t’ declared here
   72 | typedef void (*__sighandler_t) (int);
      |                ^~~~~~~~~~~~~~
unsquashfs.c:2234:25: error: passing argument 2 of ‘signal’ from incompatible pointer type [-Wincompatible-pointer-types]
 2234 |         signal(SIGALRM, sigalrm_handler);
      |                         ^~~~~~~~~~~~~~~
      |                         |
      |                         void (*)(void)
/usr/include/signal.h:88:57: note: expected ‘__sighandler_t’ {aka ‘void (*)(int)’} but argument is of type ‘void (*)(void)’
   88 | extern __sighandler_t signal (int __sig, __sighandler_t __handler)
      |                                          ~~~~~~~~~~~~~~~^~~~~~~~~
unsquashfs.c:156:6: note: ‘sigalrm_handler’ declared here
  156 | void sigalrm_handler()
      |      ^~~~~~~~~~~~~~~
/usr/include/signal.h:72:16: note: ‘__sighandler_t’ declared here
   72 | typedef void (*__sighandler_t) (int);
      |                ^~~~~~~~~~~~~~